language: python

matrix:
  include:
    - python: 2.6
    - python: 2.7
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: "nightly"
      env: PRE=--pre
  allow_failures:
    - python : "nightly"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - wget https://downloads.sourceforge.net/project/matplotlib/matplotlib-toolkits/basemap-1.0.7/basemap-1.0.7.tar.gz
  - tar -xzvf basemap-1.0.7.tar.gz
  - pushd basemap-1.0.7/geos-3.3.3 && ./configure --prefix=/usr/geos && make && sudo make install && popd
  - pushd basemap-1.0.7 && ./configure --prefix=/usr && make && sudo make install && popd
  - pip install nose coveralls numpy matplotlib flake8 geopandas
  - python setup.py install

script:
  - python run_tests.py

  - flake8 --exit-zero pysplit

after_success:
  coveralls
